apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: drift-detector
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "DriftDb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: drift-detector
data:
  API_BASE_URL: "http://backend-service:80"
  NGINX_WORKER_PROCESSES: "auto"
